### ISSUE TITLE
Gitploy V1 Roadmap

### ISSUE THREAD

**Issue by noahingh** [gitploy-io/gitploy#29]
## Objectives

Gitploy V1 provides what users need to build an delivery pipeline. 

## Roadmap
- [ ] Advanced Deployment 
  - [x] #217
  - [x] #98 
  - [x] #377
  - [ ] Support the continuous deployment (Auto deploy periodically)
  - [ ] Support configuration template 
  - [x] #379
- [ ] Deployment Safety
  - [x] #33
  - [x] #368
  - [x] #269
  - [ ] Restrict `admin` permission to a critical environment
- [x] Review
  - [x] #188
  - [x] #185
  - [ ] Provide the field for the template of a review comment
- [ ] Support `gitploy` CLI
  - [x] #219
  - [ ] #446
  - [x] #354
- [x] Lock the repository to block deploying
  - [x] #83 
  - [x] #114
  - [x] #155
- [x] #153
- [x] Documentation
  - [x] #154
- [ ] Chatops
  - [ ] Slack
  - [ ] MIcrosoft Teams
- [ ] Notification
  - [x] #261 
  - [x] Slack 
  - [ ] Microsoft Teams 
  - [x] #378
- [x] Synchronization options
  - [x] #54
  - [x] #97
- [x] #177
- [x] #131
